# Generated by Django 6.0.5 on 2026-07-16 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0044_contacthomepage_alter_patientreview_dentist"),
    ]

    operations = []
