# Generated by Django 5.2.17 on 2026-09-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRecordingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(default='Call Completed', max_length=100)),
                ('transcript', models.TextField(blank=True, default='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_recordings/%Y/%m/%d/')),
                ('save_type', models.CharField(choices=[('submit_feedback', 'Submitted Feedback'), ('without_submit', 'Without Submit (Saved on Close)')], default='without_submit', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
