# Generated by Django 5.2.17 on 2026-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecordinglog',
            name='conversation_type',
            field=models.CharField(choices=[('voice_agent', 'Voice Agent'), ('call_agent', 'Call Agent'), ('voice_call_agent', 'Voice + Call Agent')], default='voice_agent', max_length=50),
        ),
    ]
