# Generated by Django 5.2.17 on 2026-09-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_agent', '0002_voicerecordinglog_conversation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecordinglog',
            name='conversation_type',
            field=models.CharField(choices=[('voice_agent', 'Voice Agent'), ('chat_agent', 'Chat Agent'), ('chat_voice_agent', 'Chat + Voice Agent')], default='voice_agent', max_length=50),
        ),
    ]
